"""create tables and relationships

Revision ID: e765d4ef8231
Revises: 
Create Date: 2024-08-27 12:48:22.692705

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e765d4ef8231"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "coffee_shop",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("location", sa.String(), nullable=False),
        sa.Column("contact_info", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_coffee_shop_id"), "coffee_shop", ["id"], unique=False)
    op.create_table(
        "branch",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("location", sa.String(), nullable=False),
        sa.Column("deleted", sa.Boolean(), nullable=False),
        sa.Column("coffee_shop_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["coffee_shop_id"],
            ["coffee_shop.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_branch_id"), "branch", ["id"], unique=False)
    op.create_table(
        "customer",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("phone_no", sa.String(), nullable=False),
        sa.Column("coffee_shop_id", sa.Integer(), nullable=True),
        sa.Column("created", sa.TIMESTAMP(), nullable=False),
        sa.ForeignKeyConstraint(
            ["coffee_shop_id"],
            ["coffee_shop.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("phone_no", "coffee_shop_id", name="unique_phone_shop"),
    )
    op.create_index(op.f("ix_customer_id"), "customer", ["id"], unique=False)
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("first_name", sa.String(), nullable=False),
        sa.Column("last_name", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("phone_no", sa.String(), nullable=False),
        sa.Column("password", sa.String(), nullable=False),
        sa.Column("deleted", sa.Boolean(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("ADMIN", "CASHIER", "CHEF", "ORDER_RECEIVER", name="userrole"),
            nullable=False,
        ),
        sa.Column("branch_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["branch_id"],
            ["branch.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    op.create_index(op.f("ix_user_id"), "user", ["id"], unique=False)
    op.create_index(op.f("ix_user_phone_no"), "user", ["phone_no"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_phone_no"), table_name="user")
    op.drop_index(op.f("ix_user_id"), table_name="user")
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_table("user")
    op.drop_index(op.f("ix_customer_id"), table_name="customer")
    op.drop_table("customer")
    op.drop_index(op.f("ix_branch_id"), table_name="branch")
    op.drop_table("branch")
    op.drop_index(op.f("ix_coffee_shop_id"), table_name="coffee_shop")
    op.drop_table("coffee_shop")
    # ### end Alembic commands ###
