# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: user_service.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 5, 27, 2, "", "user_service.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x12user_service.proto\x12\x0buserservice"9\n\x17\x43ustomerPOSTRequestBody\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08phone_no\x18\x02 \x01(\t"\x1a\n\tTokenData\x12\r\n\x05token\x18\x01 \x01(\t"u\n\x0f\x43ustomerRequest\x12\x36\n\x08\x63ustomer\x18\x01 \x01(\x0b\x32$.userservice.CustomerPOSTRequestBody\x12*\n\ntoken_data\x18\x02 \x01(\x0b\x32\x16.userservice.TokenData"V\n\x10\x43ustomerResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08phone_no\x18\x03 \x01(\t\x12\x16\n\x0e\x63offee_shop_id\x18\x04 \x01(\x05"_\n\x17\x43ustomerResponseWrapper\x12/\n\x08\x63ustomer\x18\x01 \x01(\x0b\x32\x1d.userservice.CustomerResponse\x12\x13\n\x0bstatus_code\x18\x02 \x01(\x05\x32h\n\x0bUserService\x12Y\n\x13GetOrCreateCustomer\x12\x1c.userservice.CustomerRequest\x1a$.userservice.CustomerResponseWrapperb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "user_service_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_CUSTOMERPOSTREQUESTBODY"]._serialized_start = 35
    _globals["_CUSTOMERPOSTREQUESTBODY"]._serialized_end = 92
    _globals["_TOKENDATA"]._serialized_start = 94
    _globals["_TOKENDATA"]._serialized_end = 120
    _globals["_CUSTOMERREQUEST"]._serialized_start = 122
    _globals["_CUSTOMERREQUEST"]._serialized_end = 239
    _globals["_CUSTOMERRESPONSE"]._serialized_start = 241
    _globals["_CUSTOMERRESPONSE"]._serialized_end = 327
    _globals["_CUSTOMERRESPONSEWRAPPER"]._serialized_start = 329
    _globals["_CUSTOMERRESPONSEWRAPPER"]._serialized_end = 424
    _globals["_USERSERVICE"]._serialized_start = 426
    _globals["_USERSERVICE"]._serialized_end = 530
# @@protoc_insertion_point(module_scope)
